# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1thAj8PlYyNxteKr607uVWCxCxhUZhmUa
"""

import numpy as np
import pandas as pd

df=pd.read_csv('/content/Diabetes Dataset_Training Part.csv')

df.head(10)

df.shape

df.describe

df.dtypes

df.isnull()

df.isnull().sum()

df.corr()

corr = df[['Preg', 'Glucose', 'BPressure', 'SThickness','Insulin','BMI','DiabetesPedigreeFunction', 'Age','Outcome']].corr()['Outcome'].sort_values(ascending = False)
corr = corr.to_frame()
corr.style.background_gradient(cmap="RdYlBu")

plt.figure(figsize=(8,5))
sns.histplot(data=df, x="Glucose", hue=target_col, kde=True, bins=30, element="step")
plt.title("Distribution of Glucose by Outcome")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(12,6))
melted = pd.melt(df, id_vars=[target_col], value_vars=["Glucose","BMI","Age","Insulin"])
sns.boxplot(data=melted, x="variable", y="value", hue=target_col)
plt.title("Boxplots of Features by Outcome")
plt.show()

plt.figure(figsize=(8, 8))
sns.heatmap(df.corr(), annot=True, linewidths=0.9, fmt=".1f", cmap='RdYlBu')
plt.show()

df.drop(['SThickness'], inplace=True, axis=1)

df.head(10)

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='Outcome')
plt.title('Distribution of Diabetes Outcome')
plt.xlabel('Outcome (0: No Diabetes, 1: Diabetes)')
plt.ylabel('Count')
plt.xticks(ticks=[0, 1], labels=['No Diabetes', 'Diabetes'])
plt.show()

plt.figure(figsize=(8, 6))
sns.scatterplot(data=df, x='Glucose', y='BMI')
plt.title('Glucose vs BMI')
plt.xlabel('Glucose')
plt.ylabel('BMI')
plt.show()

df.head()

import pandas as pd

# Load the dataframe again in case of runtime reset
df = pd.read_csv('/content/Diabetes Dataset_Training Part.csv')

# Define numeric columns for outlier removal
numeric_cols = ['Preg', 'Glucose', 'BPressure', 'SThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']

# Remove outliers using IQR method for each numeric column
df_no_outliers = df.copy()

for col in numeric_cols:
    Q1 = df_no_outliers[col].quantile(0.25)
    Q3 = df_no_outliers[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    # Keep only values within bounds
    df_no_outliers = df_no_outliers[(df_no_outliers[col] >= lower_bound) & (df_no_outliers[col] <= upper_bound)]
removed_rows = len(df) - len(df_no_outliers)
remaining_rows = len(df_no_outliers)

removed_rows, remaining_rows, df_no_outliers.head()

df.shape

# Preprocessing helper: replace zeros -> NaN for certain cols, median impute and scale
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

cols_with_zero_missing = ['Glucose','BPressure','SThickness','Insulin','BMI']

def preprocess_df(input_df):
    X = input_df.drop(columns=['Outcome']).copy()
    y = input_df['Outcome'].copy()
    X[cols_with_zero_missing] = X[cols_with_zero_missing].replace(0, np.nan)
    imputer = SimpleImputer(strategy='median')
    scaler = StandardScaler()
    X_imputed = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)
    X_scaled = pd.DataFrame(scaler.fit_transform(X_imputed), columns=X.columns)
    return X_scaled, y, imputer, scaler

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X=df[[ 'Preg','Glucose', 'BPressure', 'SThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']]
y=df['Outcome']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model=LogisticRegression()
model.fit(X_train,y_train)

from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
X=df[['Preg','Glucose', 'BPressure', 'SThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']]
y=df['Outcome']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y)
X_train, X_test, y_train_encoded, y_test_encoded = train_test_split(X, y_encoded, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train_encoded)

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

y_pred_encoded = model.predict(X_test) # Add this line to get the predictions

r2 = r2_score(y_test_encoded, y_pred_encoded)
mse = mean_squared_error(y_test_encoded, y_pred_encoded)
rmse = np.sqrt(mse)

print(f"R-squared for Linear Regression: {r2}")
print(f"Mean Squared Error (MSE) for Linear Regression: {mse}")
print(f"Root Mean Squared Error (RMSE) for Linear Regression: {rmse}")

from sklearn.metrics import mean_squared_error
y_pred_encoded = model.predict(X_test)
mse = mean_squared_error(y_test_encoded, y_pred_encoded)
print(f"Mean Squared Error (MSE) for Linear Regression: {mse}")

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn import tree
import matplotlib.pyplot as plt

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = DecisionTreeClassifier(
    max_depth=3,              # Limit tree depth
    min_samples_split=4,      # Minimum samples to split a node
    random_state=42
)

model.fit(X_train, y_train)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

# Preprocess the training and testing data
X_train_scaled, y_train, imputer, scaler = preprocess_df(pd.concat([X_train, y_train], axis=1))
X_test_scaled, y_test, _, _ = preprocess_df(pd.concat([X_test, y_test], axis=1))


Model_RF = RandomForestClassifier(random_state=42, max_depth=7)
Model_RF.fit(X_train_scaled, y_train)
y_pred_RF = Model_RF.predict(X_test_scaled)

# Quick evaluation
Train_Accuracy = Model_RF.score(X_train_scaled, y_train)
Test_Accuracy = Model_RF.score(X_test_scaled, y_test)
print(f'Training accuracy: {Train_Accuracy*100:.2f} %')
print(f'Testing accuracy: {Test_Accuracy*100:.2f} %')

# Get accuracy for Logistic Regression (from cell 9QqhoAO8c_Yb)
y_pred_lr = model.predict(X_test)
accuracy_lr = accuracy_score(y_test, y_pred_lr)

# Get accuracy for Decision Tree (from cell ZbTbH9FEevQ2)
y_pred_dt = model.predict(X_test) # Note: This assumes 'model' in cell ZbTbH9FEevQ2 is the Decision Tree model
accuracy_dt = accuracy_score(y_test, y_pred_dt)

# Get metrics for Linear Regression (from cell wjKFlFlpdvnh)
# r2, mse, rmse are already calculated and available from the previous run of cell wjKFlFlpdvnh

# Get accuracy for RandomForestClassifier (from cell WGdlyXN6ezhX)
# Train_Accuracy and Test_Accuracy are already calculated and available from the previous run of cell WGdlyXN6ezhX

print("--- Model Performance Comparison ---")
print(f"Logistic Regression Accuracy: {accuracy_lr:.4f}")
print(f"Decision Tree Accuracy: {accuracy_dt:.4f}")
print(f"Random Forest Classifier Training Accuracy: {Train_Accuracy:.4f}")
print(f"Random Forest Classifier Testing Accuracy: {Test_Accuracy:.4f}")
print("\nLinear Regression Metrics (Note: Linear Regression is typically used for regression tasks, not classification):")
print(f"R-squared: {r2:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")

print("\nBased on accuracy, the RandomForestClassifier appears to be the best performing model for this classification task.")

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import numpy as np

CM = confusion_matrix(y_true=y_test, y_pred=y_pred_RF)
labels = np.unique(y_test)  # ensure labels are sorted
disp = ConfusionMatrixDisplay(confusion_matrix=CM, display_labels=labels)
disp.plot()
plt.title('Confusion Matrix')
plt.show()

print(classification_report(y_test, y_pred_RF))

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

Accuracy_RF = accuracy_score(y_test, y_pred_RF)
print(f'➤➤➤ Accuracy Score : {Accuracy_RF * 100 : .2f} %\n')


# Precision = TP / (TP + FP)
Precision_RF = precision_score(y_test, y_pred_RF)
print(f'➤➤➤ Precision Score : {Precision_RF * 100 : .2f} %\n')


# Recall/Sensitivity = TP / (TP + FN)
Recall_RF = recall_score(y_test, y_pred_RF)
print(f'➤➤➤ Recall Score : {Recall_RF * 100 : .2f} %\n')


# F1 Score = 2 × ((Precision * Recall) / (Precision + Recall))
F1_Score_RF = f1_score(y_test, y_pred_RF)
print(f'➤➤➤ F1 Score : {F1_Score_RF * 100 : .2f} %\n')

metrics = ['Accuracy', 'Precision', 'Recall', 'F1 Score']
scores = [Accuracy_RF, Precision_RF, Recall_RF, F1_Score_RF]

# Plotting the bar chart
plt.figure(figsize=(10, 6))
plt.bar(metrics, scores, color=['blue', 'green', 'red', 'orange'])
plt.title('Performance Metrics of Random Forest Model')
plt.xlabel('Metrics')
plt.ylabel('Score')
plt.ylim(0.1, 1)
plt.yticks([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])
plt.grid(axis='y', alpha=1)
plt.show()

#Final Evaluation
Classifiers = ['Decision Tree', 'Random Forest']
Accuracies = [(accuracy_dt * 100), (Accuracy_RF * 100)]
plt.bar(Classifiers, Accuracies, color=['green', 'brown'])
plt.title('Model Accuracy Comparison')
plt.ylabel('Accuracy (%)')
plt.ylim(70, 100)
plt.grid(axis='y', alpha=1)
plt.show()